/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";



export default function Mug(props) {

    useThree((state) => {
        console.log(state)
    })

    const { camera } = useThree()
    camera.position.set(0,0,-10)
    console.log(camera)

  const group = useRef();
  const { nodes, materials } = useGLTF("/Mug.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0.2, -0.09, -0.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.MugWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.MugStoneware}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Mug.gltf");
